### ISSUE TITLE
Any chance to update?

### ISSUE THREAD

**Issue by luboq** [mralbobo/stardew-gate-opener#1]
Seems not working anymore in my Stardew Valley v1.11 and SMAPI-0.40.1.1.

**Comment by mralbobo** [comment]
Just tried it, seems fine...

**Comment by luboq** [comment]
Sorry, I misunderstood its effect, I thought it opens doors OF BUILDING automatically, like my farm house etc. I just realize it only opens fence gate automatically. Thanks!
